name: Nodejs App CI/CD.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code 
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t cloudedemo-nodejs .  

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image to Docker Hub
      run: |
        docker tag cloudedemo-nodejs ${{ secrets.DOCKER_USERNAME }}/cloudedemo-nodejs:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cloudedemo-nodejs:latest


  deploy:

    runs-on: ubuntu-latest

    needs: build-and-push 

    steps:

    - name: Deploy to ubuntuwebserver
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ubuntuwebserver }}
        username: ${{ secrets.login }}
        key: ${{ secrets.password }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/clo-nodejs:latest
          sudo docker stop cloudedemo-nodejs || true
          sudo docker rm cloudedemo-nodejs || true
          sudo docker run -d -p 3004:3000 --name=cloudedemo-nodejs ${{ secrets.DOCKER_USERNAME }}/cloudedemo-nodejs:latest
          sudo docker ps