name: Nodejs App CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t cloudedemo-nodejs .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Utilisez la dernière version de l'action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image to Docker Hub
      run: |
        docker tag cloudedemo-nodejs ${{ secrets.DOCKER_USERNAME }}/cloudedemo-nodejs:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cloudedemo-nodejs:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Test network connectivity
      run: ping -c 4 192.168.1.101

    - name: Deploy to ubuntuwebserver
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }} # 192.168.1.101
        username: ${{ secrets.SSH_USERNAME }} # saberdev
        password: ${{ secrets.SSH_PASSWORD }} # saberdev
        port: 22
        timeout: 120s
        command_timeout: 15m
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cloudedemo-nodejs:latest
          sudo docker stop cloudedemo-nodejs || true
          sudo docker rm cloudedemo-nodejs || true
          sudo docker run -d -p 3004:3000 --name=cloudedemo-nodejs ${{ secrets.DOCKER_USERNAME }}/cloudedemo-nodejs:latest
          sudo docker ps
